name: Deploy to AWS

on:
  push:
    branches:
      - main  # Runs when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Initialize Terraform
        run: terraform init

      - name: Import Existing S3 Bucket (if not already in state)
        run: |
            terraform state list | grep aws_s3_bucket.website_bucket || terraform import aws_s3_bucket.website_bucket my-static-website-bucket-123452055

      - name: Import Existing CloudFront Distribution (if not already in state)
        run: |
            terraform state list | grep aws_cloudfront_distribution.website_cdn || terraform import aws_cloudfront_distribution.website_cdn E1N7ZSIV9WHJVG
          

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve

      - name: Sync Website Files to S3
        run: aws s3 sync . s3://my-static-website-bucket-123452055 --delete --exclude ".terraform/*" --exclude "*.tf*" --exclude ".git/*" --exclude ".gitignore" --exclude README.md --exclude .terraform.* --exclude .git/* --exclude .github/*
        
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
